plugins { id 'com.android.application' }
android {
    namespace 'com.zycgod.habitcheckin'
    compileSdk 34
    defaultConfig {
        applicationId "com.zycgod.habitcheckin"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
